"use client";

import type { SourceItem } from "@/types/day9";
import { ExternalLink } from "lucide-react";

export function SourcesList({ sources }: { sources: SourceItem[] }) {
  if (sources.length === 0) return null;

  return (
    <div className="sources-footer border-t border-[var(--border)] pt-4 mt-6">
      <h4 className="text-[11px] font-bold uppercase tracking-[0.1em] text-[var(--text-secondary)] mb-2">
        Sources
      </h4>
      <ul className="space-y-1">
        {sources.map((source, i) => (
          <li key={i} className="flex items-start gap-2 text-[11px]">
            <ExternalLink className="w-3 h-3 text-[var(--text-tertiary)] mt-0.5 shrink-0" />
            <div className="min-w-0">
              <a
                href={source.url}
                target="_blank"
                rel="noopener noreferrer"
                className="text-[var(--text-secondary)] hover:text-[var(--foreground)] truncate block"
              >
                {source.title}
              </a>
              <span className="text-[var(--text-tertiary)]">
                {source.queryType}
                {source.date ? ` · ${source.date}` : ""}
              </span>
            </div>
          </li>
        ))}
      </ul>
      <p className="text-[11px] text-[var(--text-tertiary)] mt-3">
        Generated by MeetingPrep · Powered by Serper + Gemini Flash
      </p>
    </div>
  );
}
