'use client'

import { useState } from 'react'
import { Mail, Loader2 } from 'lucide-react'
import { toast } from 'sonner'
import type { CompetitorAnalysis, Weakness } from '@/types'

function formatAnalysisForEmail(analysis: CompetitorAnalysis): { subject: string; body: string } {
  const date = new Date(analysis.created_at).toLocaleDateString()
  const subject = `Competitor intel: ${analysis.domain} — ${date}`

  const weaknessText = (analysis.weaknesses as Weakness[])
    ?.map((w, i) => `${i + 1}. [${w.severity.toUpperCase()}] ${w.title}\n   ${w.description}\n   Opportunity: ${w.opportunity}`)
    .join('\n\n') || 'N/A'

  const body = `COMPETITOR INTELLIGENCE REPORT
${analysis.domain} — ${date}
━━━━━━━━━━━━━━━━━━━━━━━━━━━

VALUE PROPOSITION (${analysis.vp_confidence} confidence)
${analysis.value_proposition || 'N/A'}
Evidence: ${analysis.vp_evidence || 'N/A'}

TARGET ICP (${analysis.icp_confidence} confidence)
${analysis.target_icp || 'N/A'}
Signals: ${analysis.icp_signals?.join(', ') || 'N/A'}

PRICING MODEL (${analysis.pricing_confidence} confidence)
${analysis.pricing_model || 'N/A'}
Signals: ${analysis.pricing_signals?.join(', ') || 'N/A'}

GO-TO-MARKET (${analysis.gtm_confidence} confidence)
${analysis.gtm_motion || 'N/A'}
Signals: ${analysis.gtm_signals?.join(', ') || 'N/A'}

EXPLOITABLE WEAKNESSES
${weaknessText}

${analysis.analysis_notes ? `NOTES: ${analysis.analysis_notes}` : ''}

Generated by CompetitorRadar`

  return { subject, body }
}

export function GmailDraftButton({ analysis }: { analysis: CompetitorAnalysis }) {
  const [loading, setLoading] = useState(false)

  async function handleClick() {
    setLoading(true)
    try {
      const { subject, body } = formatAnalysisForEmail(analysis)
      const mailtoUrl = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
      window.open(mailtoUrl, '_blank')
      toast.success('Opening email draft...')
    } catch {
      toast.error('Failed to create draft')
    } finally {
      setLoading(false)
    }
  }

  return (
    <button
      onClick={handleClick}
      disabled={loading}
      className="flex items-center gap-2 rounded-lg border border-border bg-surface px-4 py-2.5 text-sm font-medium text-text-primary transition-colors hover:bg-surface-raised disabled:opacity-50"
    >
      {loading ? (
        <Loader2 className="h-4 w-4 animate-spin" />
      ) : (
        <Mail className="h-4 w-4" />
      )}
      Draft intel report
    </button>
  )
}
