"use client";

import { useState, useCallback } from "react";
import { toast } from "sonner";

export function useGmailDraft() {
  const [isLoading, setIsLoading] = useState(false);

  const createDraft = useCallback(
    async (tweetContent: string, articleTitle: string, articleUrl: string) => {
      setIsLoading(true);

      try {
        // The Gmail MCP tool is available via the MCP integration
        // This is called client-side through the MCP protocol
        const subject = `Tweet draft: ${articleTitle}`;
        const body = `${tweetContent}\n\n---\nGenerated by TweetCraft from: ${articleUrl}`;

        // Attempt Gmail MCP call
        // Note: In Claude Code environment, this uses the MCP tool directly
        // In production web app, gracefully fall back to clipboard
        if (typeof window !== "undefined" && "ClaudeTools" in window) {
          // MCP available — call Gmail create draft
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          const tools = (window as unknown as Record<string, unknown>).ClaudeTools as Record<string, (...args: unknown[]) => Promise<unknown>>;
          await tools["gmail_create_draft"]({ subject, body });
          toast.success("Draft created in Gmail ✓", {
            action: {
              label: "Open Gmail",
              onClick: () => window.open("https://mail.google.com", "_blank"),
            },
          });
        } else {
          // Fallback: copy formatted email text
          const emailText = `Subject: ${subject}\n\n${body}`;
          await navigator.clipboard.writeText(emailText);
          toast.success("Copied email-ready text to clipboard");
        }
      } catch {
        // Final fallback
        try {
          await navigator.clipboard.writeText(tweetContent);
          toast.info("Gmail unavailable — copied tweet to clipboard instead");
        } catch {
          toast.error("Could not create Gmail draft");
        }
      } finally {
        setIsLoading(false);
      }
    },
    []
  );

  return { createDraft, isLoading };
}
